### ISSUE TITLE
1.14: test suite fails

### ISSUE THREAD

**Issue by kloczek** [linux-test-project/lcov#64]
<pre>+ /usr/bin/make -O -j4 test -j1
<b>Creating coverage files (2 tests, 5 source files)</b>
  Source tree ......... done (950 lines, 50 functions, 3428 branches)
  Full coverage ....... done
  Target coverage ..... done
  Partial coverage .... done
  Zero coverage ....... done
<b>Starting tests</b>
<b>genhtml_output_zero ..........</b> [<font color="#00CD00">pass</font>] (time 0.3s, mem 12.4MB)
<b>genhtml_output_full ..........</b> [<font color="#00CD00">pass</font>] (time 0.3s, mem 12.3MB)
<b>genhtml_output_target ........</b> [<font color="#00CD00">pass</font>] (time 0.3s, mem 12.5MB)
<b>genhtml_output_part1 .........</b> [<font color="#00CD00">pass</font>] (time 0.3s, mem 12.4MB)
<b>genhtml_output_part2 .........</b> [<font color="#00CD00">pass</font>] (time 0.3s, mem 12.4MB)
<b>genhtml_output_combined ......</b> [<font color="#00CD00">pass</font>] (time 0.8s, mem 13.4MB)
<b>lcov_add_zero ................</b> [<font color="#00CD00">pass</font>] (time 0.3s, mem 12.2MB)
<b>lcov_add_zero2 ...............</b> [<font color="#00CD00">pass</font>] (time 0.5s, mem 13.3MB)
<b>lcov_add_full ................</b> [<font color="#00CD00">pass</font>] (time 0.3s, mem 12.2MB)
<b>lcov_add_full2 ...............</b> [<font color="#00CD00">pass</font>] (time 0.5s, mem 13.4MB)
<b>lcov_add_part ................</b> [<font color="#00CD00">pass</font>] (time 0.3s, mem 12.3MB)
<b>lcov_add_part2 ...............</b> [<font color="#00CD00">pass</font>] (time 0.5s, mem 13.5MB)
<b>lcov_add_concatenated4 .......</b> [<font color="#00CD00">pass</font>] (time 0.5s, mem 12.7MB)
<b>lcov_diff_apply ..............</b> [<font color="#CD0000">fail</font>] (time 0.6s, mem 17.7MB)
  COMMAND ....: &quot;./diff_test&quot;
  OUTPUT .....: 
    Capturing coverage data from .
    Found gcov version: 9.0.1
    Scanning . for .gcda files ...
    geninfo: WARNING: /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcov_diff/old/prog.gcno: Overlong record at end of file!
    Found 1 data files in .
    Processing prog.gcda
    geninfo: WARNING: cannot find an entry for prog.c##9d444dbee7ca7875c029725315296e84.gcov in .gcno file, skipping file!
    Finished .info-file creation
    ...
    Skipping 12 more lines (see /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/test.log)
<b>lcov_version .................</b> [<font color="#00CD00">pass</font>] (time 0.1s, mem 11.7MB)
<b>lcov_help ....................</b> [<font color="#00CD00">pass</font>] (time 0.1s, mem 11.5MB)
<b>lcov_summary_zero ............</b> [<font color="#00CD00">pass</font>] (time 0.2s, mem 12.3MB)
<b>lcov_summary_full ............</b> [<font color="#00CD00">pass</font>] (time 0.2s, mem 12.1MB)
<b>lcov_summary_target ..........</b> [<font color="#00CD00">pass</font>] (time 0.2s, mem 12.3MB)
<b>lcov_summary_part1 ...........</b> [<font color="#00CD00">pass</font>] (time 0.2s, mem 12.4MB)
<b>lcov_summary_part2 ...........</b> [<font color="#00CD00">pass</font>] (time 0.2s, mem 12.2MB)
<b>lcov_summary_concatenated ....</b> [<font color="#00CD00">pass</font>] (time 0.2s, mem 12.4MB)
<b>lcov_summary_concatenated2 ...</b> [<font color="#00CD00">pass</font>] (time 0.2s, mem 12.4MB)
<b>23 tests executed</b>, <font color="#00CD00">22 passed</font>, <font color="#CD0000">1 failed</font>, 0 skipped (time 7.8s, mem 292.8MB)
Result log stored in /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/test.log
make[1]: *** [common.mak:34: exit] Error 1
</pre>

**Comment by oberpar** [comment]
This is due to missing GCC 9 support in lcov. See also issue #58

**Comment by oberpar** [comment]
This should be fixed with commit 75fbae1.

**Comment by kloczek** [comment]
Just tested dist 1.14 + all patches up to master and test suite still fails.
```
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Creating coverage files (2 tests, 5 source files)
  Source tree ......... done (950 lines, 50 functions, 3428 branches)
  Full coverage ....... done
  Target coverage ..... done
  Partial coverage .... done
  Zero coverage ....... done
Starting tests
genhtml_output_zero .......... [pass] (time 0.1s, mem 12.8MB)
  COMMAND ....: "genhtml --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info -o out_zero/"
  OUTPUT .....:
    Reading data file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info
    Found 5 entries.
    Found common filename prefix "/home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/src"
    Writing .css and .png files.
    Generating output.
    Processing file build/info/mem_c.h
    Processing file config/basic/mem.h
    Processing file target/misc.c
    Processing file tools/build/misc.c
    Processing file www/list.c
    Writing directory view page.
    Overall coverage rate:
      lines......: 0.0% (0 of 950 lines)
      functions..: 0.0% (0 of 50 functions)
      branches...: 0.0% (0 of 3428 branches)
  EXITCODE ...: 0
genhtml_output_full .......... [pass] (time 0.1s, mem 12.7MB)
  COMMAND ....: "genhtml --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info -o out_full/"
  OUTPUT .....:
    Reading data file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info
    Found 5 entries.
    Found common filename prefix "/home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/src"
    Writing .css and .png files.
    Generating output.
    Processing file build/info/mem_c.h
    Processing file config/basic/mem.h
    Processing file target/misc.c
    Processing file tools/build/misc.c
    Processing file www/list.c
    Writing directory view page.
    Overall coverage rate:
      lines......: 100.0% (950 of 950 lines)
      functions..: 100.0% (50 of 50 functions)
      branches...: 100.0% (3428 of 3428 branches)
  EXITCODE ...: 0
genhtml_output_target ........ [pass] (time 0.1s, mem 12.6MB)
  COMMAND ....: "genhtml --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info -o out_target/"
  OUTPUT .....:
    Reading data file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info
    Found 5 entries.
    Found common filename prefix "/home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/src"
    Writing .css and .png files.
    Generating output.
    Processing file build/info/mem_c.h
    Processing file config/basic/mem.h
    Processing file target/misc.c
    Processing file tools/build/misc.c
    Processing file www/list.c
    Writing directory view page.
    Overall coverage rate:
      lines......: 80.0% (760 of 950 lines)
      functions..: 60.0% (30 of 50 functions)
      branches...: 20.0% (685 of 3428 branches)
  EXITCODE ...: 0
genhtml_output_part1 ......... [pass] (time 0.1s, mem 12.8MB)
  COMMAND ....: "genhtml --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info -o out_part1/"
  OUTPUT .....:
    Reading data file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info
    Found 5 entries.
    Found common filename prefix "/home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/src"
    Writing .css and .png files.
    Generating output.
    Processing file build/info/mem_c.h
    Processing file config/basic/mem.h
    Processing file target/misc.c
    Processing file tools/build/misc.c
    Processing file www/list.c
    Writing directory view page.
    Overall coverage rate:
      lines......: 40.5% (385 of 950 lines)
      functions..: 54.0% (27 of 50 functions)
      branches...: 9.7% (333 of 3428 branches)
  EXITCODE ...: 0
genhtml_output_part2 ......... [pass] (time 0.1s, mem 12.7MB)
  COMMAND ....: "genhtml --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info -o out_part2/"
  OUTPUT .....:
    Reading data file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info
    Found 5 entries.
    Found common filename prefix "/home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/src"
    Writing .css and .png files.
    Generating output.
    Processing file build/info/mem_c.h
    Processing file config/basic/mem.h
    Processing file target/misc.c
    Processing file tools/build/misc.c
    Processing file www/list.c
    Writing directory view page.
    Overall coverage rate:
      lines......: 39.5% (375 of 950 lines)
      functions..: 6.0% (3 of 50 functions)
      branches...: 10.3% (352 of 3428 branches)
  EXITCODE ...: 0
genhtml_output_combined ...... [pass] (time 0.4s, mem 13.6MB)
  COMMAND ....: "./genhtml_test /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info"
  OUTPUT .....:
    Reading data file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info
    Found 5 entries.
    Found common filename prefix "/home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/src"
    Writing .css and .png files.
    Generating output.
    Processing file build/info/mem_c.h
    Processing file config/basic/mem.h
    Processing file target/misc.c
    Processing file tools/build/misc.c
    Processing file www/list.c
    Writing directory view page.
    Overall coverage rate:
      lines......: 80.0% (760 of 950 lines)
      functions..: 60.0% (30 of 50 functions)
      branches...: 20.0% (685 of 3428 branches)
    Reading data file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info
    Reading data file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info
    Found 5 entries.
    Found common filename prefix "/home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/src"
    Writing .css and .png files.
    Generating output.
    Processing file build/info/mem_c.h
    Processing file config/basic/mem.h
    Processing file target/misc.c
    Processing file tools/build/misc.c
    Processing file www/list.c
    Writing directory view page.
    Overall coverage rate:
      lines......: 80.0% (760 of 950 lines)
      functions..: 60.0% (30 of 50 functions)
      branches...: 20.0% (685 of 3428 branches)
  EXITCODE ...: 0
lcov_add_zero ................ [pass] (time 0.1s, mem 12.6MB)
  COMMAND ....: "./add_test 1 /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info"
  OUTPUT .....:
    + echo 'Adding files...'
    Adding files...
    + lcov --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info -o add_zero.info
    Combining tracefiles.
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info
    Writing data to add_zero.info
    Summary coverage rate:
      lines......: 0.0% (0 of 950 lines)
      functions..: 0.0% (0 of 50 functions)
      branches...: 0.0% (0 of 3428 branches)
    + echo 'Normalizing result...'
    Normalizing result...
    + norminfo add_zero.info 1
    + echo 'Comparing with reference...'
    Comparing with reference...
    + diff -u /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info norm_add_zero.info
  EXITCODE ...: 0
lcov_add_zero2 ............... [pass] (time 0.2s, mem 13.7MB)
  COMMAND ....: "./add_test 1 /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info"
  OUTPUT .....:
    + echo 'Adding files...'
    Adding files...
    + lcov --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info -o add_zero.info
    Combining tracefiles.
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info
    Writing data to add_zero.info
    Summary coverage rate:
      lines......: 0.0% (0 of 950 lines)
      functions..: 0.0% (0 of 50 functions)
      branches...: 0.0% (0 of 3428 branches)
    + echo 'Normalizing result...'
    Normalizing result...
    + norminfo add_zero.info 1
    + echo 'Comparing with reference...'
    Comparing with reference...
    + diff -u /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info norm_add_zero.info
  EXITCODE ...: 0
lcov_add_full ................ [pass] (time 0.1s, mem 12.7MB)
  COMMAND ....: "./add_test 1 /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info"
  OUTPUT .....:
    + echo 'Adding files...'
    Adding files...
    + lcov --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info -o add_full.info
    Combining tracefiles.
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info
    Writing data to add_full.info
    Summary coverage rate:
      lines......: 100.0% (950 of 950 lines)
      functions..: 100.0% (50 of 50 functions)
      branches...: 100.0% (3428 of 3428 branches)
    + echo 'Normalizing result...'
    Normalizing result...
    + norminfo add_full.info 1
    + echo 'Comparing with reference...'
    Comparing with reference...
    + diff -u /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info norm_add_full.info
  EXITCODE ...: 0
lcov_add_full2 ............... [pass] (time 0.2s, mem 13.7MB)
  COMMAND ....: "./add_test 0.5 /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info"
  OUTPUT .....:
    + echo 'Adding files...'
    Adding files...
    + lcov --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info -o add_full.info
    Combining tracefiles.
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info
    Writing data to add_full.info
    Summary coverage rate:
      lines......: 100.0% (950 of 950 lines)
      functions..: 100.0% (50 of 50 functions)
      branches...: 100.0% (3428 of 3428 branches)
    + echo 'Normalizing result...'
    Normalizing result...
    + norminfo add_full.info 0.5
    + echo 'Comparing with reference...'
    Comparing with reference...
    + diff -u /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info norm_add_full.info
  EXITCODE ...: 0
lcov_add_part ................ [pass] (time 0.1s, mem 12.6MB)
  COMMAND ....: "./add_test 1 /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info"
  OUTPUT .....:
    + echo 'Adding files...'
    Adding files...
    + lcov --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info -o add_part1.info
    Combining tracefiles.
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info
    Writing data to add_part1.info
    Summary coverage rate:
      lines......: 40.5% (385 of 950 lines)
      functions..: 54.0% (27 of 50 functions)
      branches...: 9.7% (333 of 3428 branches)
    + echo 'Normalizing result...'
    Normalizing result...
    + norminfo add_part1.info 1
    + echo 'Comparing with reference...'
    Comparing with reference...
    + diff -u /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info norm_add_part1.info
  EXITCODE ...: 0
lcov_add_part2 ............... [pass] (time 0.2s, mem 13.7MB)
  COMMAND ....: "./add_test 1 /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info"
  OUTPUT .....:
    + echo 'Adding files...'
    Adding files...
    + lcov --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info -a /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info -o add_target.info
    Combining tracefiles.
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info
    Reading tracefile /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info
    Writing data to add_target.info
    Summary coverage rate:
      lines......: 80.0% (760 of 950 lines)
      functions..: 60.0% (30 of 50 functions)
      branches...: 20.0% (685 of 3428 branches)
    + echo 'Normalizing result...'
    Normalizing result...
    + norminfo add_target.info 1
    + echo 'Comparing with reference...'
    Comparing with reference...
    + diff -u /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info norm_add_target.info
  EXITCODE ...: 0
lcov_add_concatenated4 ....... [pass] (time 0.2s, mem 13.1MB)
  COMMAND ....: "./add_test 0.25 /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info concatenated.info"
  OUTPUT .....:
    + echo 'Adding files...'
    Adding files...
    + lcov --config-file /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/lcovrc -a concatenated.info -o add_target.info
    Combining tracefiles.
    Reading tracefile concatenated.info
    Writing data to add_target.info
    Summary coverage rate:
      lines......: 80.0% (760 of 950 lines)
      functions..: 60.0% (30 of 50 functions)
      branches...: 20.0% (685 of 3428 branches)
    + echo 'Normalizing result...'
    Normalizing result...
    + norminfo add_target.info 0.25
    + echo 'Comparing with reference...'
    Comparing with reference...
    + diff -u /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info norm_add_target.info
  EXITCODE ...: 0
lcov_diff_apply .............. [fail] (time 0.2s, mem 18.8MB)
  COMMAND ....: "./diff_test"
  OUTPUT .....:
    Capturing coverage data from .
    Can't locate PerlIO/gzip.pm in @INC (you may need to install the PerlIO::gzip module) (@INC contains: /usr/local/lib64/perl5/5.30 /usr/local/share/perl5/5.30 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/tkloczko/rpmbuild/BUILD/lcov-1.14/bin/geninfo line 62.
    BEGIN failed--compilation aborted at /home/tkloczko/rpmbuild/BUILD/lcov-1.14/bin/geninfo line 62.
    make[3]: *** [Makefile:6: prog.info] Error 2
    Error: Failed to compile old source
  EXITCODE ...: 1
lcov_version ................. [pass] (time 0.0s, mem 11.8MB)
  COMMAND ....: "lcov --version"
  OUTPUT .....:
    lcov: LCOV version 1.14
  EXITCODE ...: 0
lcov_help .................... [pass] (time 0.0s, mem 11.8MB)
  COMMAND ....: "lcov --help"
  OUTPUT .....:
    Usage: lcov [OPTIONS]

    Use lcov to collect coverage data from either the currently running Linux
    kernel or from a user space application. Specify the --directory option to
    get coverage data for a user space program.

    Misc:
      -h, --help                      Print this help, then exit
      -v, --version                   Print version number, then exit
      -q, --quiet                     Do not print progress messages

    Operation:
      -z, --zerocounters              Reset all execution counts to zero
      -c, --capture                   Capture coverage data
      -a, --add-tracefile FILE        Add contents of tracefiles
      -e, --extract FILE PATTERN      Extract files matching PATTERN from FILE
      -r, --remove FILE PATTERN       Remove files matching PATTERN from FILE
      -l, --list FILE                 List contents of tracefile FILE
          --diff FILE DIFF            Transform tracefile FILE according to DIFF
          --summary FILE              Show summary coverage data for tracefiles

    Options:
      -i, --initial                   Capture initial zero coverage data
      -t, --test-name NAME            Specify test name to be stored with data
      -o, --output-file FILENAME      Write data to FILENAME instead of stdout
      -d, --directory DIR             Use .da files in DIR instead of kernel
      -f, --follow                    Follow links when searching .da files
      -k, --kernel-directory KDIR     Capture kernel coverage data only from KDIR
      -b, --base-directory DIR        Use DIR as base directory for relative paths
          --convert-filenames         Convert filenames when applying diff
          --strip DEPTH               Strip initial DEPTH directory levels in diff
          --path PATH                 Strip PATH from tracefile when applying diff
          --(no-)checksum             Enable (disable) line checksumming
          --(no-)compat-libtool       Enable (disable) libtool compatibility mode
          --gcov-tool TOOL            Specify gcov tool location
          --ignore-errors ERRORS      Continue after ERRORS (gcov, source, graph)
          --no-recursion              Exclude subdirectories from processing
          --to-package FILENAME       Store unprocessed coverage data in FILENAME
          --from-package FILENAME     Capture from unprocessed data in FILENAME
          --no-markers                Ignore exclusion markers in source code
          --derive-func-data          Generate function data from line data
          --list-full-path            Print full path during a list operation
          --(no-)external             Include (ignore) data for external files
          --config-file FILENAME      Specify configuration file location
          --rc SETTING=VALUE          Override configuration file setting
          --compat MODE=on|off|auto   Set compat MODE (libtool, hammer, split_crc)
          --include PATTERN           Include files matching PATTERN
          --exclude PATTERN           Exclude files matching PATTERN

    For more information see: http://ltp.sourceforge.net/coverage/lcov.php
  EXITCODE ...: 0
lcov_summary_zero ............ [pass] (time 0.1s, mem 12.6MB)
  COMMAND ....: "./check_counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info"
  OUTPUT .....:
    Comparing --summary output for /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.info and /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/zero.counts:
    line hit: 0 == 0
    line found: 950 == 950
    functions hit: 0 == 0
    functions found: 50 == 50
    branches hit: 0 == 0
    branches found: 3428 == 3428
  EXITCODE ...: 0
lcov_summary_full ............ [pass] (time 0.1s, mem 12.7MB)
  COMMAND ....: "./check_counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info"
  OUTPUT .....:
    Comparing --summary output for /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.info and /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/full.counts:
    line hit: 950 == 950
    line found: 950 == 950
    functions hit: 50 == 50
    functions found: 50 == 50
    branches hit: 3428 == 3428
    branches found: 3428 == 3428
  EXITCODE ...: 0
lcov_summary_target .......... [pass] (time 0.1s, mem 12.5MB)
  COMMAND ....: "./check_counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info"
  OUTPUT .....:
    Comparing --summary output for /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.info and /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.counts:
    line hit: 760 == 760
    line found: 950 == 950
    functions hit: 30 == 30
    functions found: 50 == 50
    branches hit: 685 == 685
    branches found: 3428 == 3428
  EXITCODE ...: 0
lcov_summary_part1 ........... [pass] (time 0.1s, mem 12.6MB)
  COMMAND ....: "./check_counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info"
  OUTPUT .....:
    Comparing --summary output for /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.info and /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part1.counts:
    line hit: 385 == 385
    line found: 950 == 950
    functions hit: 27 == 27
    functions found: 50 == 50
    branches hit: 333 == 333
    branches found: 3428 == 3428
  EXITCODE ...: 0
lcov_summary_part2 ........... [pass] (time 0.1s, mem 12.6MB)
  COMMAND ....: "./check_counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info"
  OUTPUT .....:
    Comparing --summary output for /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.info and /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/part2.counts:
    line hit: 375 == 375
    line found: 950 == 950
    functions hit: 3 == 3
    functions found: 50 == 50
    branches hit: 352 == 352
    branches found: 3428 == 3428
  EXITCODE ...: 0
lcov_summary_concatenated .... [pass] (time 0.1s, mem 12.9MB)
  COMMAND ....: "./check_counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.counts concatenated.info"
  OUTPUT .....:
    Comparing --summary output for concatenated.info and /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.counts:
    line hit: 760 == 760
    line found: 950 == 950
    functions hit: 30 == 30
    functions found: 50 == 50
    branches hit: 685 == 685
    branches found: 3428 == 3428
  EXITCODE ...: 0
lcov_summary_concatenated2 ... [pass] (time 0.1s, mem 12.10MB)
  COMMAND ....: "./check_counts /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.counts concatenated2.info"
  OUTPUT .....:
    Comparing --summary output for concatenated2.info and /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/target.counts:
    line hit: 760 == 760
    line found: 950 == 950
    functions hit: 30 == 30
    functions found: 50 == 50
    branches hit: 685 == 685
    branches found: 3428 == 3428
  EXITCODE ...: 0
23 tests executed, 22 passed, 1 failed, 0 skipped (time 4.2s, mem 301.4MB)
Result log stored in /home/tkloczko/rpmbuild/BUILD/lcov-1.14/test/test.log
make[1]: *** [common.mak:34: exit] Error 1
make: *** [Makefile:122: test] Error 2
```

**Comment by oberpar** [comment]
You'll need to install the `PerlIO::gzip` and `JSON` Perl modules.

**Comment by kloczek** [comment]
Closing.
Seems it works with those modules installed :)

**Comment by GitMensch** [comment]
There is a text "closing" but the issue is still open - can I suggest to close it?

**Comment by kloczek** [comment]
Just tested new version and all looks good 👍 
Closing and thank you 😄
